apiVersion: v1
kind: Pod
metadata:
  name: mynapp-pod-liveness-404
spec:
  containers:
  - image: c1t1d0s7/myweb
    name: mynapp
    ports:
    - containerPort: 8081
      protocol: TCP
    livenessProbe:
      httpGet:
        path: /
        port: 8082