apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mynapp-rc-exp
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - mynapp-rs-exp
      - key: env
        operator: Exists
  template:
    metadata:
      labels:
        app: mynapp-rs-exp
        env: dev
    spec:
      containers:
      - image: c1t1d0s7/myweb
        name: mynapp
        ports:
        - containerPort: 8080