apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mynapp-rs-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mynapp-rs-front
      tier: frontend
  template:
    metadata:
      labels:
        app: mmynapp-rs-front
        tier: frontend
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: tier
                operator: In
                values:
                - frontend
            topologyKey: "kubenetes.io/hostname"
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: tier
                operator: In
                values:
                - cache
            topologyKey: "kubenetes.io/hostname"
      containers:
      - name: mynapp
        image: c1t1d0s7/myweb
