apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mydb-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: mydb
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80