apiVersion: v1
kind: Pod
metadata:
  name: mynapp-pod-wd
  labels:
    app: mynapp-pod-wd
spec:
  containers:
  - name: pod-wd
    image: wordpress:latest
    ports:
    - containerPort: 80
      protocol: TCP
    volumeMounts:
    - name: wd-vol
      mountPath: /var/www/html
    env: 
    - name: WORDPRESS_DB_HOST
      value: "mynapp-svc-headless"
    - name: WORDPRESS_DB_USER
      value: "wp-admin"
    - name: WORDPRESS_DB_PASSWORD
      value: "1234"
    - name: WORDPRESS_DB_NAME
      value: "wordpress"      
  volumes:
  - name: wd-vol
    persistentVolumeClaim:
      claimName: mynapp-pvc-dy-cephfs