apiVersion: v1
kind: Pod
metadata:
  name: mynapp-pod
spec:
  containers:
  - name: mynapp
    image: shhan0226/web:centWeb
    env:
    - name: WEBPORT
      value: "8080"
    ports:
    - containerPort: 8080
      protocol: TCP
