apiVersion: v1
kind: Pod
metadata:
  name: mynapp-pod-cm
spec:
  containers:
    - image: c1t1d0s7/myweb:customport
      name: mynapp
      env:
      - name: NODE_PORT
        valueFrom:
          configMapKeyRef:
            name: mynapp-pod-options
            key: nodeport
      - name: MESSAGE
        valueFrom:
          configMapkeyRef:
            name: mynapp-pod-options
            key: message
      args:
      - $(MESSAGE)
      ports:
      - containerPort: 8080
        protocol: TCP  