apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mynapp-rs-headless
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mynapp-rs-headless
  template:
    metadata:
      labels:
        app: mynapp-rs-headless
    spec:
      containers:
      - name: mynapp
        image: c1t1d0s7/myweb
        ports:
        - containerPort: 8080
        