apiVersion: v1
kind: Service
metadata:
  name: nmynapp-svc-np
spec:
  ports:
  - name: mynapp-http
    port: 80
    targetPort: 8080
  - name: mynapp-https
    port: 443
    targetPort: 8443
  selector:
    app: mynapp-rs