apiVersion: app/v1
kind: ReplicaSet
metadata:
  name: mynapp-rs-nport
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mynapp-rs-nport
  template:
    metadata:
      labels:
        app: mynapp-rs-nport
    spec:
      containers:
      - name: mynapp
        image: c1t1d0s7/myweb
        ports:
        - name: mynapp-http
          containerPort: 8080

        
