#!/bin/bash
echo -e "\n[endpoints]"
kubectl get endpoints
echo "_____________________________________"


echo -e "\n[ingresses]"
kubectl describe ingresses
echo "_____________________________________"

echo -e "\n[hpa]"
kubectl get hpa
echo "_____________________________________"


echo -e "\n[Config]"
kubectl get configmaps
echo "_____________________________________"

echo -e "\n[secrets]"
kubectl get secrets 
echo "_____________________________________"

echo -e "\n[storageClass]"
kubectl get storageclasses.storage.k8s.io
echo "_____________________________________"

echo -e "\n[node-labels]"
kubectl get nodes --show-labels

echo -e "\n\n>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
echo -e ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n\n"


echo "[Get all]"
kubectl get all
echo "_____________________________________"

echo -e "\n[Pvc]"
kubectl get persistentvolumeclaims
echo "_____________________________________"

echo -e "\n[Service]"
kubectl get services
echo "_____________________________________"

echo -e "\n[node-pod]"
kubectl get po -o wide





