apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mywd-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mywd-dep
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70