kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: myadmin-cluster
subjects:
- kind: ServiceAccount
  name: myadmin
  apiGroup: ""
  namespace: default
roleRef:
  kind: ClusterRole
  name: read-cluster-pod
  apiGroup: "rbac.authorization.k8s.io"