kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: myuser1-reaad-default
  namespace: default
subjects:
- kind: ServiceAccount
  name: myuser1
  apiGroup: ""
  namespace: default
roleRef:
  kind: Role
  name: read-default-pod
  apiGroup: rbac.authorization.k8s.io