apiVersion: v1
kind: PersistentVolume
metadata:
  name: mynapp-pv-nfs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nfs-volume
    server: 192.168.56.11 #master1
