apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mynapp-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mynapp-rs
  template:
    metadata:
      labels:
        app: mynapp-rs
    spec:
      containers:
      - name: mynapp
        image: httpd:latest
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          exec:
            command:
              - ls
              - /var/local/apache2/htdocs/ready
        livenessProbe:
          httpGet:
            path: /
            port: 80
        volumeMounts:
        - name: readiness
          mountPath: /var/local/apache2/htdocs/ready
      volumes:
      - name: readiness
        configMap:
          name: readiness-conf
