apiVersion: v1
kind: Service
metadata:
  name: mynapp-svc-headless
  labels:
    name: mynapp-svc-headless
spec:
  clusterIP: None
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mydb