apiVersion: v1
kind: ReplicationController
metadata:
  name: mynapp-rc-v1
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: mynapp-rc
    spec:
      containers:
      - name: mynapp
        image: c1t1d0s7/myweb:v1
        ports:
        - containerPort: 8080