apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynapp-deploy
  labels:
    app: mynapp-deploy
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 20
  replicas: 3
  selector:
    matchLabels:
      app: mynapp-deploy
  template:
    metadata:
      labels:
        app: mynapp-deploy
    spec:
      containers:
      - image: c1t1d0s7/myweb:v1
        name: mynapp
        ports:
        - containerPort: 8080
